name: Manual workflow

on: [push]

jobs:
  greet:
    runs-on: namespace-profile-default
    timeout-minutes: 25
    steps:
      - run: |
          woorkersd=$(date +"%Y%m%d%H%M%S")
          echo $woorkersd
